export const DisplayEmployeeInfo = {
   
    EMPLOYEE_REQUEST: 'EMPLOYEE_REQUEST',
    EMPLOYEE_SUCCESS: 'EMPLOYE_SUCCESS',
    EMPLOYEE_FAILURE: 'EMPLOYEE_FAILURE', 
    EMPLOYEE_LOGIN:'EMPLOYEE_LOGIN',
    EMPLOYEE_LOGIN_SUCCESS:'EMPLOYEE_LOGIN_SUCCESS',
    EMPLOYEE_LOGIN_FAILURE:'EMPLOYEE_LOGIN_FAILURE'
};
